// Authored pairs are [zh_cn, en_us]. Family expansion keeps physical details specific to each material and shape.
export const lore = {
  dirt: ['松散的褐土夹着细根，捏碎后很适合填平地面。', 'Loose brown soil holds fine roots and crumbles readily into uneven ground.'],
  grass_block: ['薄薄的草皮连着湿土，铺好后能慢慢接成一片绿地。', 'A thin turf holds damp soil together and can spread into a continuous lawn.'],
  coarse_dirt: ['土里掺着许多碎石，踩实后也不容易长出草来。', 'Grit interrupts the soil throughout, keeping a trodden patch clear of grass.'],
  rooted_dirt: ['细根在土块里绕成一团，锄开就能把根须分出来。', 'Fine roots wind through the earth and separate when worked with a hoe.'],
  podzol: ['腐叶覆着暗色土层，带着林地潮湿的气味，种蘑菇正合适。', 'Leaf litter covers dark soil with a damp woodland smell, suitable for growing mushrooms.'],
  mycelium: ['灰紫色菌丝密密铺在表面，足以让蘑菇在亮处生长。', 'Grey-purple threads cover the surface closely enough to support mushrooms in the light.'],
  mud: ['湿泥黏在手上不肯脱落，掺些麦秆才能压得结实。', 'Wet mud clings to the hand; a little wheat helps pack it into useful building material.'],
  clay: ['细腻的灰泥没有多少砂粒，揉开后适合制砖烧陶。', 'Fine grey clay carries little grit and works well into bricks or pottery.'],
  sand: ['浅色砂粒从指缝间流走，装窑能烧出透亮的玻璃。', 'Pale grains run between the fingers and melt into clear glass in a furnace.'],
  red_sand: ['砂粒裹着一层铁红色，烧玻璃时倒和普通沙子一样好用。', 'An iron-red coating colours the grains, though they make glass as readily as ordinary sand.'],
  gravel: ['大小不一的石子滚得很散，翻找时偶尔能摸到一片燧石。', 'Uneven pebbles roll apart easily, occasionally revealing a flint among them.'],
  soul_sand: ['褐色细砂里浮着模糊的面孔，脚踩进去会陷得很慢。', 'Indistinct faces mark the brown grains, which hold a footstep back.'],
  soul_soil: ['暗色土壤干而松，点起的火焰会呈现冷蓝色。', 'Dark soil is dry and loose, carrying a cold blue flame when lit.'],
  netherrack: ['红色岩石满是细孔，敲起来很脆，却能让火一直烧着。', 'Porous red rock breaks readily under a pick and keeps an open flame burning.'],
  end_stone: ['淡黄的岩面坑坑洼洼，拿来砌筑比看起来结实。', 'Pits cover the pale yellow surface, which builds more solidly than it looks.'],
  obsidian: ['黑亮的断面锋利而沉重，想完整采下来需要一把好镐。', 'Glossy black fractures are sharp and heavy, requiring a good pick to recover intact.'],
  crying_obsidian: ['紫色液滴沿黑色岩面缓缓渗出，适合用在重生锚上。', 'Purple droplets seep across the dark face, material suited to a respawn anchor.'],
  basalt: ['深灰岩柱的纹理顺着长边延伸，竖着铺设很齐整。', 'Long dark-grey grain follows the column and lays neatly in an upright course.'],
  polished_basalt: ['磨平的玄武岩露出笔直纹理，适合收齐柱子的边角。', 'Polished basalt shows straight grain that gives a column a clean outline.'],
  smooth_basalt: ['细密的灰色岩面少了棱纹，用作平整衬面十分朴素。', 'Fine grey stone has lost its ridges and makes a plain, even facing.'],
  calcite: ['乳白的晶粒挤在一起，砌在深色石材旁显得干净。', 'Milky crystals press together into a clean contrast beside dark stone.'],
  magma_block: ['黑色硬壳裂着橙红的缝，站上去最好隔着厚实的鞋底。', 'Orange-red seams split the black crust; a bare step is a poor choice.'],
  dripstone_block: ['棕色岩面带着水蚀的小孔，下面还能接出尖长的石锥。', 'Water has pitted the brown rock, which can support pointed growth underneath.'],
  pointed_dripstone: ['石锥一层层收向尖端，接在洞顶可以收集滴水。', 'Layers taper to a sharp point, useful for gathering drips from a cave ceiling.'],
  ice: ['透明冰面裹着细白的气泡，铺成通道时脚下格外滑。', 'Fine white bubbles sit inside clear ice that makes a very slippery passage.'],
  packed_ice: ['挤得严实的冰层泛着蓝白光，放在灯旁也能保持原样。', 'Tightly packed layers glow blue-white and keep their shape beside a lamp.'],
  blue_ice: ['深蓝冰体几乎看不见气泡，船底经过时滑得尤其远。', 'Deep blue ice holds scarcely a bubble and carries a boat particularly far.'],
  snow: ['松软的雪粒铺成薄层，用锹就能轻松收拢。', 'Soft grains settle in a thin layer, easily gathered with a shovel.'],
  snow_block: ['压实的雪块凉而细密，用来堆墙比散雪省事。', 'Packed snow is cold and close-grained, easier to build a wall with than loose powder.'],
  moss_block: ['厚实的绿苔盖住整个表面，撒些骨粉就能铺开。', 'Thick green moss covers every side and spreads with a little bone meal.'],
  moss_carpet: ['薄苔柔软贴地，铺在石上也不显得突兀。', 'A soft, low mat of moss sits naturally even over stone.'],
  cobweb: ['细丝层层交错，粘住衣角后要费些力气才能挣开。', 'Layers of fine silk catch a sleeve and take some effort to pull free.'],
  kelp: ['长而滑的叶片带着海水气味，烘干后能当作干粮。', 'Long slippery blades smell of seawater and dry into simple provisions.'],
  seagrass: ['柔细的草叶离水便垂下来，带去喂海龟倒很合适。', 'Fine blades droop out of water but make suitable feed for turtles.'],
  sea_pickle: ['矮小的软管挤成一簇，留在水里才亮得起来。', 'Short soft tubes cluster together and give their light only underwater.'],
  vine: ['细茎牵着宽叶，贴在墙面就能给攀爬留个落手处。', 'Fine stems carry broad leaves and give a wall a useful climbing hold.'],
  twisting_vines: ['蓝绿色藤条盘着细节向上长，搭高架时能借它落脚。', 'Blue-green vines curl upward, providing footholds along a tall structure.'],
  weeping_vines: ['暗红藤蔓一节节垂下，挂在高处便是一条细软的梯子。', 'Dark red joints hang downward into a slender, yielding ladder.'],
  glow_lichen: ['苍白薄片紧贴岩面，亮度不高，却能照清脚边。', 'Pale flakes cling to stone, giving just enough light to make out a nearby step.'],
  hanging_roots: ['一撮细根沾着湿土，垂在顶下能添些林地的样子。', 'Fine roots carry traces of wet soil and bring a woodland look to an overhang.'],
  spore_blossom: ['宽大的粉色花瓣向下舒展，细小孢子会缓缓落满周围。', 'Broad pink petals open downward and let fine spores drift through the room.'],
  big_dripleaf: ['宽叶撑在长茎顶端，能借一步，却撑不住久站。', 'A broad leaf rests on a tall stem, sound for a step but not a long pause.'],
  small_dripleaf: ['两片嫩叶贴着短茎，施过骨粉才够长成落脚的叶台。', 'Two tender leaves hug a short stem that needs bone meal to grow into a stepping leaf.'],
  pink_petals: ['轻薄的粉瓣贴着草地，铺得疏些也很好看。', 'Thin pink petals lie close to the grass and look well even in a sparse patch.'],
  lily_pad: ['扁圆的叶面浮在水上，脚踩过去时能撑住分量。', 'A flat round leaf floats on the water and supports a passing step.'],
  cactus: ['厚皮里存着水分，外面的刺却不适合徒手碰。', 'Thick skin stores moisture behind spines that discourage an ungloved hand.'],
  sugar_cane: ['青绿长节里含着甜汁，做纸和熬糖都用得着。', 'Sweet juice fills the green joints, useful for both paper and sugar.'],
  bamboo: ['空心竹节轻而直，绑脚手架和加工木料都方便。', 'Hollow joints are light and straight, convenient for scaffolding or worked timber.'],
  dead_bush: ['枯枝干得发脆，掰下来还能凑几根木棍。', 'Dry twigs snap easily and can still supply a few sticks.'],
  short_grass: ['短草根部带着泥屑，留一片就能遮住裸土。', 'Soil clings to the short roots; a patch is enough to cover bare ground.'],
  tall_grass: ['细长草叶挤在一起，长到齐腰时容易挡住视线。', 'Long narrow blades crowd together and obscure the view at waist height.'],
  fern: ['细分的绿叶沿中脉展开，放在树荫下很自然。', 'Divided green fronds open along a central rib and sit naturally in shade.'],
  large_fern: ['宽大的羽状叶层层展开，适合填满林间的空处。', 'Broad feathered fronds spread in layers to fill a woodland gap.'],
  brown_mushroom: ['褐色菌盖柔软略湿，切进炖汤里很合适。', 'A soft, slightly damp brown cap is useful sliced into stew.'],
  red_mushroom: ['红菌盖上散着白点，配上另一种蘑菇才能煮出熟悉的汤。', 'White spots mark the red cap, best paired with the other mushroom for a familiar stew.'],
  brown_mushroom_block: ['厚菌盖的切面松软多孔，铺成伞顶有现成的弧度。', 'The thick cap is soft and porous within, already shaped for a broad canopy.'],
  red_mushroom_block: ['红白斑点留在外皮，内侧像海绵，搭棚时很醒目。', 'A red spotted skin covers a spongy inside, making a conspicuous shelter.'],
  mushroom_stem: ['浅色菌柄细密而轻，叠起来能做一根素净的柱子。', 'Pale, fine-grained stalk is light and stacks into a plain column.'],
  crimson_roots: ['暗红根须分成细枝，簇在菌岩旁很相称。', 'Dark red roots fork into fine sprays that suit a patch of nylium.'],
  warped_roots: ['蓝绿根须扭着向外伸，种在诡异菌旁能连成一片。', 'Twisted blue-green roots spread outward into a matching bed beside warped fungi.'],
  nether_sprouts: ['矮小嫩芽透着青色，铺在下界菌地上不占多少高度。', 'Short blue-green shoots cover fungal ground without adding much height.'],
  crimson_fungus: ['红色菌盖结实厚重，放在绯红菌岩上可以催成大株。', 'A thick red cap can be encouraged into a huge fungus on crimson nylium.'],
  warped_fungus: ['青蓝菌盖边缘卷起，除了种植也能引来炽足兽。', 'The blue-green cap curls at its edges and attracts striders as well as growing into a fungus.'],
  crimson_nylium: ['红色菌层紧紧覆住岩石，适合作绯红菌的苗床。', 'A close red fungal layer covers the rock, making a bed for crimson fungi.'],
  warped_nylium: ['青色菌层在暗岩上铺开，诡异菌扎在这里才长得大。', 'Blue-green growth spreads over dark rock where warped fungi can grow tall.'],
  nether_wart_block: ['暗红颗粒压成厚块，做菌冠衬面很合适，拆不回原料。', 'Dark red grains press into a thick canopy block that cannot be unpacked into its ingredients.'],
  warped_wart_block: ['青绿颗粒结成硬团，搭在菌柄上就有了宽厚的顶。', 'Blue-green grains form a firm mass that gives a fungus a broad, thick crown.'],
  bee_nest: ['薄蜡片包着天然巢室，搬运前得照顾好里面的住户。', 'Thin wax encloses natural chambers whose occupants need care when the nest is moved.'],
  beehive: ['木壳里排着整齐巢格，留出入口便能安置蜂群。', 'Neat comb cells line the wooden casing, ready for a colony with a clear entrance.'],
  turtle_egg: ['浅色硬壳布着绿斑，放回沙上才有机会孵开。', 'Green flecks mark a pale shell that needs sand beneath it to hatch.'],
  sniffer_egg: ['厚壳上覆着苔色斑块，放在苔藓上会更快裂开。', 'Moss-coloured patches cover a thick shell that hatches faster on a moss block.'],
  sculk: ['深色表面浮着青点，踩上去没有石头那样的硬响。', 'Blue-green points dot the dark surface, softer underfoot than bare stone.'],
  sculk_vein: ['细薄脉络攀满表面，贴在洞壁上几乎不占地方。', 'Thin veins cling to a surface and coat a cave wall with little bulk.'],
  sculk_catalyst: ['浅色顶面托着暗脉，附近有生物死去时会向外蔓延。', 'A pale crown sits over dark veins that spread when a creature dies nearby.'],
  sculk_shrieker: ['几根浅色突起围住暗孔，搬离原处后已唤不来监守者。', 'Pale prongs surround a dark opening that can no longer summon a warden once moved.'],
  pumpkin: ['厚橙皮包着纤维和种子，雕空或做馅都用得上。', 'Thick orange skin encloses fibres and seeds, useful hollowed out or made into filling.'],
  carved_pumpkin: ['刀口在厚皮上刻出一张脸，戴起来能避开末影人的目光。', 'Cut edges make a face in the thick rind, a mask that avoids an enderman\'s gaze.'],
  melon: ['绿色硬皮裹着多汁的红瓤，切开能分成好几份。', 'A firm green rind encloses juicy red flesh that divides into several slices.'],
  chorus_flower: ['浅色硬瓣护住中心，种在末地石上还能长出枝节。', 'Pale firm petals protect a centre that grows new branches on end stone.'],
  azalea: ['矮枝密密托着小叶，适合沿着小径种成一排。', 'Short branches hold close small leaves, suitable for a row along a path.'],
  flowering_azalea: ['小小的粉花藏在密叶里，不用长高也能点缀庭院。', 'Small pink flowers sit among dense leaves and brighten a yard without growing tall.'],
  azalea_leaves: ['细枝连着紧密小叶，修成矮篱很方便。', 'Fine twigs hold close small leaves, convenient for a low hedge.'],
  flowering_azalea_leaves: ['粉花夹在紧实叶团里，做花篱时不用再添别的花。', 'Pink blossoms sit in compact foliage that makes a flowering hedge on its own.'],
  mangrove_roots: ['弯曲木根交成网眼，填水后仍能看清缝隙。', 'Curved roots cross into a mesh whose gaps remain visible when filled with water.'],
  muddy_mangrove_roots: ['湿泥塞满了根须间隙，垒起来像一段结实的河岸。', 'Wet mud fills the tangled roots into material resembling a firm riverbank.'],
  mangrove_propagule: ['细长胚轴垂着绿尖，泡在水里也能扎根成树。', 'A long green-tipped shoot can take root even while standing in water.'],
  crafting_table: ['台面被刀痕分成方格，摊开材料就能做些完整的物件。', 'Knife marks divide the top into squares, with room to assemble a complete piece of work.'],
  furnace: ['石砌炉膛积着黑灰，烧矿和做饭都够用。', 'Black ash lines the stone firebox, adequate for smelting ore or cooking a meal.'],
  blast_furnace: ['铁皮围紧炉口，烧矿比石炉快，做饭却用不上。', 'Iron plates enclose the mouth, smelting ore quickly but serving poorly as a kitchen.'],
  smoker: ['木框围着熏烤炉膛，处理食物很快，却熔不开矿石。', 'A wooden frame surrounds the smoking chamber, quick for food but unable to smelt ore.'],
  stonecutter: ['圆刃嵌在石台中，修整石阶和边角比整批合成省料。', 'A round blade rises from the stone bed, trimming steps and edges with less waste.'],
  loom: ['木框拉着整齐的经线，织旗面的图案比徒手省事。', 'Even warp threads stretch across the wooden frame, making banner patterns easier to weave.'],
  cartography_table: ['平整桌面留着地图格线，复制和缩放图纸都方便。', 'Map lines mark a flat top suited to copying and scaling charts.'],
  fletching_table: ['台边刻着羽枝图样，摆在村里能供制箭师认领。', 'Feather markings line the edge of a workbench a village fletcher can claim.'],
  smithing_table: ['暗色台面包着金属边，升级装备和压入纹饰都有地方落手。', 'Metal edges bind the dark top, with room to upgrade equipment and apply a trim.'],
  grindstone: ['粗磨轮夹在支架上，能磨去附魔，也能拼修两件旧工具。', 'A coarse wheel sits in its frame, ready to strip enchantments or repair two worn tools together.'],
  enchanting_table: ['深色台座托着一本会翻页的书，周围留给书架的位置很要紧。', 'A turning book rests on the dark base; room for nearby shelves matters.'],
  anvil: ['厚铁台面平而沉，修补装备和敲定名字都经得起。', 'A broad iron face is flat and heavy enough for repairing equipment or setting a name.'],
  chipped_anvil: ['台角已经崩掉一块，敲打还能继续，只是余日不多。', 'A piece has broken from the corner; work can continue, though not indefinitely.'],
  damaged_anvil: ['深裂纹穿过铁台，下一次落锤也许就撑不住了。', 'Deep cracks cross the iron face, which may not survive another job.'],
  beacon: ['透亮外壳包着发光核心，架在矿物基座上才能照得远。', 'A clear casing surrounds a bright core that needs a mineral foundation to reach far.'],
  conduit: ['海晶碎片围着坚硬核心，浸在完整框架中才能护住潜水的人。', 'Prismarine pieces surround a firm core that protects divers inside a submerged frame.'],
  respawn_anchor: ['暗色框架里留着发光的空槽，充入萤石便能在下界落脚。', 'A luminous recess sits in the dark frame, ready for glowstone and a foothold in the Nether.'],
  lodestone: ['灰石外面箍着金属边，指南针碰过就会认准这里。', 'Metal bands bind the grey stone, giving a touched compass a fixed point to follow.'],
  lectern: ['斜木板托住书页，放在路口读写都不必弯腰。', 'A sloped wooden rest holds a book open at a comfortable reading height.'],
  bookshelf: ['厚书紧紧排进木格，既填墙面，也能给附魔台添些学问。', 'Thick books fill the wooden bays, furnishing a wall and lending knowledge to an enchanting table.'],
  chiseled_bookshelf: ['六格书槽分别开好，常翻的几本可以各留一个位置。', 'Six separate book slots give frequently used volumes their own place.'],
  composter: ['木桶四周留着缝隙，攒下的植物边料能慢慢积成骨粉。', 'Gaps ring the wooden bin where plant scraps build into a little bone meal.'],
  barrel: ['木板用箍束紧，盖口朝外就能在狭窄地方取放物品。', 'Bands hold the staves together, with an end opening useful in a narrow storeroom.'],
  chest: ['木板围住一只空箱，盖子上方留空才开得顺。', 'Boards enclose a plain box whose lid needs clear space above it.'],
  ender_chest: ['暗色箱壳边缘透出紫光，开口总通向自己那一份储藏。', 'Purple light escapes the dark casing, opening onto the owner\'s own storage each time.'],
  cauldron: ['厚铁锅壁围得很深，接水、盛雪或储岩浆都稳当。', 'Deep iron sides hold water, snow or lava without a fuss.'],
  bell: ['黄铜钟身敲起来清脆，悬在村口能把人叫回屋里。', 'The brass body rings clearly enough to call villagers indoors.'],
  campfire: ['木柴在矮架里慢烧，围着烤食物时不必另装燃料。', 'Logs smoulder in a low rack that cooks food without fresh fuel.'],
  soul_campfire: ['蓝色火苗沿木柴跳动，火边很烫，光却照不了太远。', 'Blue flames move along the logs, hot nearby but modest in reach.'],
  jukebox: ['木壳上的窄槽刚好容下一张唱片，放进去便能听完整一曲。', 'A narrow slot in the wooden case takes a disc and plays its full recording.'],
  flower_pot: ['小陶盆口沿厚实，装一株小花就不显空了。', 'A thick rim surrounds the little clay pot, filled well by a single small flower.'],
  decorated_pot: ['宽陶腹四面留着纹样，能作摆设，也能收起一类小物件。', 'Four patterned faces enclose a broad clay body, decorative and useful for storing one kind of item.'],
  scaffolding: ['竹杆撑着薄平台，向上接时不必一层层垫实。', 'Bamboo poles support a thin platform that extends upward without a solid tower beneath it.'],
  ladder: ['短木档固定在两根长条间，贴墙搭起就能省下楼梯的地方。', 'Short rungs join two rails, saving the space a staircase would occupy.'],
  armor_stand: ['细木架托着石底座，卸下的盔甲可以整套挂好。', 'A slender wooden frame rests on a stone base, ready to hold a complete set of armour.'],
  item_frame: ['薄木框绷着皮革底，挂一件样品便能认出箱里装什么。', 'A leather backing stretches across the thin wooden frame, enough for a storage sample.'],
  glow_item_frame: ['框内的皮面带着亮意，暗处也能看清挂着的物件。', 'A lit leather backing keeps its displayed item visible in a dark corner.'],
  painting: ['薄画布绷在木框上，墙面宽些便能挂出大幅图景。', 'Thin canvas stretches over a wooden frame, with a wider scene for a broader wall.'],
  torch: ['煤末裹在木棍一端，插下就能照亮眼前的一小片。', 'Coal coats one end of a stick, lighting a small patch once set down.'],
  soul_torch: ['木棍顶着一簇蓝火，亮得克制，却能让猪灵避开。', 'A small blue flame tops the stick, modest in brightness and enough to turn piglins away.'],
  lantern: ['铁框护着暖光，挂在门前不会占住通路。', 'An iron frame guards a warm light that hangs clear of a doorway.'],
  soul_lantern: ['冷蓝火光收在铁壳里，吊在檐下显得安静。', 'Cold blue fire sits inside an iron casing, a subdued light beneath an eave.'],
  sea_lantern: ['乳白晶面发着均匀的光，嵌进水池边也照得清楚。', 'Milky crystal gives an even light that remains clear beside a pool.'],
  glowstone: ['金黄晶粒结在一起，铺进顶棚就能省去火把。', 'Golden crystals bind together into ceiling lights that save room for torches.'],
  end_rod: ['细白灯杆两端齐整，狭窄的走廊也放得下。', 'A narrow white light has neat ends and fits even a cramped passage.'],
  chain: ['黑铁环一个扣着一个，吊灯和悬架都能借它相连。', 'Dark iron links join in sequence, useful for hanging lamps and suspended work.'],
  shroomlight: ['橙色菌体里散着亮点，整块藏在叶丛中也能透出光来。', 'Bright points fill the orange fungus and shine through surrounding leaves.'],
  ochre_froglight: ['淡黄光从柔和的表面透出，铺成灯带也不刺眼。', 'Pale yellow light passes through a soft-looking face, comfortable in a row of lamps.'],
  pearlescent_froglight: ['浅粉光泽沿表面分布，嵌进白墙里很柔和。', 'A pale pink sheen spreads across the face and sits gently in a white wall.'],
  verdant_froglight: ['浅绿灯面透着匀光，适合压在庭院小径的边上。', 'The pale green face gives even light along the edge of a garden path.'],
  jack_o_lantern: ['雕空的橙皮里藏着火光，既能照明，也留着南瓜的笑脸。', 'Firelight fills the hollow orange rind, keeping both a lamp and a carved face.'],
};

function pair(id, zh, en) {
  if (lore[id]) throw new Error(`duplicate authored lore: ${id}`);
  lore[id] = [zh, en];
}

const trees = {
  oak: ['橡木', 'oak', '宽厚的绿叶', 'broad green leaves'],
  spruce: ['云杉', 'spruce', '深绿的针叶', 'dark green needles'],
  birch: ['白桦', 'birch', '细薄的亮绿叶', 'thin bright-green leaves'],
  jungle: ['丛林木', 'jungle tree', '浓密的大叶', 'dense broad leaves'],
  acacia: ['金合欢', 'acacia', '疏展的灰绿叶', 'open grey-green leaves'],
  dark_oak: ['深色橡木', 'dark oak', '层叠的深绿叶', 'overlapping dark-green leaves'],
  mangrove: ['红树', 'mangrove', '厚实的湿绿叶', 'thick damp-green leaves'],
  cherry: ['樱花树', 'cherry tree', '细密的粉色花瓣', 'close pink blossom'],
};
for (const [id, [zh, en, leavesZh, leavesEn]] of Object.entries(trees)) {
  pair(`${id}_leaves`, `${leavesZh}连在细枝上，保留一团就能补齐${zh}树冠。`, `${leavesEn[0].toUpperCase()}${leavesEn.slice(1)} hold to fine twigs, useful for filling a gap in a ${en} canopy.`);
  if (id !== 'mangrove') pair(`${id}_sapling`, `${zh}幼苗的细根还很短，留足周围的空间才能长开。`, `Short fine roots support this ${en} sapling, which needs room around it to grow.`);
}
const flowers = {
  allium: ['紫色小花聚成圆球，插在花坛边缘很醒目。', 'Small purple flowers gather into a ball, distinct along a flowerbed edge.'],
  azure_bluet: ['浅白小花围着黄心，低低一簇很适合点缀路边。', 'Pale little petals surround yellow centres in a low roadside patch.'],
  blue_orchid: ['蓝花沿弯茎展开，移出沼泽也能在庭院里添一抹冷色。', 'Blue flowers open along a bent stem, bringing a cool colour from the swamp to a garden.'],
  cornflower: ['细蓝花瓣向外散开，磨成染料时颜色也很清楚。', 'Fine blue petals spread outward and make a distinct blue dye.'],
  dandelion: ['细黄瓣围成小盘，随手一捧就能配出黄色染料。', 'Fine yellow petals form a small disc and yield a handful of yellow dye.'],
  lilac: ['淡紫花穗挤在高枝上，放在矮花后面也看得见。', 'Pale purple clusters stand on tall stems, visible behind a lower flowerbed.'],
  lily_of_the_valley: ['白色小铃沿细茎垂下，看着干净，却不宜放进食物里。', 'Small white bells hang along a fine stem, clean-looking but unsuitable for a meal.'],
  orange_tulip: ['橙色花杯托在直茎上，排列整齐时颜色很暖。', 'An orange flower cup rests on a straight stem, warm in an ordered row.'],
  oxeye_daisy: ['白瓣绕着饱满黄心，种在草地里朴素耐看。', 'White petals circle a full yellow centre, plain and pleasing in grass.'],
  peony: ['粉色花瓣叠得厚厚的，一株就能填起花坛的空处。', 'Thick layers of pink petals fill a gap in a bed with a single plant.'],
  pink_tulip: ['浅粉花瓣收成窄杯，贴着白墙种下很柔和。', 'Pale pink petals fold into a narrow cup, gentle beside a white wall.'],
  poppy: ['薄红瓣托着深色花心，磨开便是一份红色染料。', 'Thin red petals hold a dark centre and grind into a portion of red dye.'],
  red_tulip: ['红色花杯边缘齐整，成排栽下像细小的路标。', 'Neat edges line the red cup, making little markers when planted in a row.'],
  rose_bush: ['红花挤在带刺的高枝上，围成花篱很合适。', 'Red blooms crowd thorny tall stems, suitable for a flowering hedge.'],
  sunflower: ['宽黄瓣围着沉甸甸的花盘，花面能帮人认清东方。', 'Broad yellow petals surround a weighty disc whose face points out the east.'],
  white_tulip: ['白色花杯沿茎挺立，点在深色叶丛里很清楚。', 'A white cup stands on its stem, clear among dark leaves.'],
  wither_rose: ['黑瓣枯而完整，碰到就会受伤，摆放时要留出距离。', 'Black petals are withered but intact, harmful to touch and best given space.'],
  torchflower: ['红黄花瓣卷成火苗的形状，看着明亮却不能代替灯。', 'Red and yellow petals curl into a flame shape, bright in colour but unable to light a room.'],
  pitcher_plant: ['宽叶托着鼓起的囊袋，高高一株就能填满墙边。', 'Broad leaves support a swollen pitcher, tall enough to fill a space beside a wall.'],
};
Object.assign(lore, flowers);
const coral = { brain: ['粉红的褶纹', 'pink folds'], bubble: ['紫色的圆泡', 'purple rounded nodes'], fire: ['红色的细枝', 'fine red branches'], horn: ['黄色的角枝', 'yellow horn-shaped branches'], tube: ['蓝色的管孔', 'blue tube openings'] };
for (const [id, [zh, en]] of Object.entries(coral)) {
  for (const [suffix, formZh, formEn, useZh, useEn] of [
    ['', '小簇', 'small cluster', '水下的小景', 'a small underwater scene'],
    ['_block', '厚块', 'thick mass', '珊瑚礁的基底', 'the base of a reef'],
    ['_fan', '扇面', 'fan', '礁壁边缘', 'the edge of a reef wall'],
  ]) {
    pair(`${id}_coral${suffix}`, `${zh}组成${formZh}，布置${useZh}时得留在水里。`, `The ${formEn} carries ${en} and needs water when used for ${useEn}.`);
    pair(`dead_${id}_coral${suffix}`, `${formZh}已经失去原来${zh}的颜色，只留下灰白骨架，做干燥造景仍能用。`, `The ${formEn} has lost its ${en}, leaving a grey skeleton still useful in a dry display.`);
  }
}
for (const [id, zh, en, useZh, useEn] of [
  ['small_amethyst_bud', '尖端才露出浅紫', 'a pale tip barely showing', '只能先作细小装饰', 'a small decorative detail'],
  ['medium_amethyst_bud', '几根紫色晶尖开始分开', 'several purple points beginning to separate', '装点洞壁正好', 'a detail on a cave wall'],
  ['large_amethyst_bud', '粗大的晶尖尚未完全展开', 'thick points not yet fully spread', '成簇摆放很醒目', 'a conspicuous grouped display'],
  ['amethyst_cluster', '透亮晶尖已经长齐', 'clear points fully formed', '敲碎可以取得紫水晶碎片', 'a source of amethyst shards when broken'],
]) pair(id, `${zh}，${useZh}。`, `With ${en}, this growth serves as ${useEn}.`);

Object.assign(lore, {
  beef: ['深红肉块纹理紧实，切口留着肉汁，烤熟之后更顶饿。', 'Firm grain runs through the deep-red cut, with juices at the edge; cooking makes it more filling.'],
  chicken: ['浅色鸡肉裹着薄皮，处理时得留心，烤熟才吃更稳妥。', 'Thin skin covers pale flesh that calls for care and is better eaten cooked.'],
  mutton: ['红肉间夹着白脂，架在火上烤能把香味带出来。', 'White fat runs through the red meat and brings out its flavour over a fire.'],
  porkchop: ['厚肉边带着一圈白脂，烤过之后能顶上一顿。', 'A ring of white fat borders the thick cut, a filling meal once cooked.'],
  rabbit: ['小块瘦肉挂着细骨，熟透以后适合放进炖汤。', 'A little lean meat clings to fine bones, suitable for stew after cooking.'],
  cod: ['淡色鱼肉贴着细骨，整条烤熟就是一顿简单的饭。', 'Pale flesh holds to fine bones, a simple meal when the whole fish is cooked.'],
  salmon: ['橙红鱼肉分成细层，烤过后比生吃饱足些。', 'Orange-red flesh divides into fine layers and fills more of a meal when cooked.'],
  tropical_fish: ['鲜艳鱼鳞裹着少量细肉，填肚子不多，喂美西螈更合适。', 'Bright scales surround little flesh, modest food but useful feed for axolotls.'],
  pufferfish: ['鼓起的鱼身带着细刺，肉虽能入口，毒性却不能小看。', 'Fine spines cover the swollen body, edible in a narrow sense but seriously poisonous.'],
  cooked_chicken: ['薄皮烤成浅金色，下面的肉容易撕开，吃起来不费劲。', 'Thin skin has browned lightly over flesh that tears apart without much effort.'],
  cooked_mutton: ['边缘的油脂已经烤香，肉纹仍清楚，一块就能顶饿。', 'The fat has browned around a clearly grained cut, substantial enough to quiet hunger.'],
  cooked_porkchop: ['厚肉表面收成褐色，脂肪封住部分肉汁，适合带着赶路。', 'A browned surface and rendered fat retain some juice, useful provisions for a journey.'],
  cooked_rabbit: ['瘦肉烤得紧实，份量虽小，放进炖汤里仍有用处。', 'The lean meat has cooked firm, a small portion still useful in a stew.'],
  cooked_cod: ['白色鱼肉沿纹理剥开，味道清淡，吃一条很快。', 'White flesh flakes along its grain, mild enough to finish without fuss.'],
  cooked_salmon: ['橙色鱼肉烤后更紧，薄薄一层油让它不那么干。', 'Cooking firms the orange flesh, with a thin film of oil keeping it from drying out.'],
  beetroot: ['暗红根块带着湿土，洗净能吃，凑几颗也能熬汤。', 'Damp soil coats the dark-red root, edible when washed and useful gathered for soup.'],
  carrot: ['橙色根部清脆结实，既能当饭，也能留作下一季的种。', 'A firm orange root has a clean crunch, serving as food or planting stock.'],
  potato: ['薄褐皮裹着硬实的薯肉，进炉烤熟会好吃许多。', 'Thin brown skin surrounds firm flesh that improves considerably in a furnace.'],
  poisonous_potato: ['绿斑透过薯皮浮出来，切面也不干净，不该当成普通土豆。', 'Green patches show through the skin and spoil the cut, a poor substitute for an ordinary potato.'],
  baked_potato: ['皱皮下面的薯肉松软，掰开带着淀粉的香气，朴素而管饱。', 'Soft flesh sits under a wrinkled skin, opening with a starchy scent and a filling portion.'],
  melon_slice: ['薄皮托住多汁的红瓤，清甜解口，却算不上大餐。', 'A thin rind holds juicy red flesh, refreshing but short of a full meal.'],
  glow_berries: ['橙黄浆果皮薄带光，摘下后仍适合作一小份零食。', 'Thin orange-yellow skins hold a soft glow, still a small snack once picked.'],
  chorus_fruit: ['紫色硬皮包着松软果肉，入口以后落脚的位置未必照旧。', 'Purple skin encloses soft flesh that may leave the eater standing elsewhere.'],
  popped_chorus_fruit: ['烘过的果壳轻而干脆，已经不作食物，更适合加工紫珀。', 'The popped shell is light and crisp, useful for purpur work rather than a meal.'],
  dried_kelp: ['薄叶烘得皱而脆，嚼得快，饿的时候得多吃几片。', 'Thin blades dry wrinkled and crisp, quick to chew but needed in numbers when hungry.'],
  cookie: ['小圆饼里嵌着可可碎，酥口但分量不大，适合随手垫一口。', 'Cocoa flecks sit in the little biscuit, crisp but small enough for only a quick bite.'],
  pumpkin_pie: ['厚馅压在薄饼底上，南瓜的甜味平和，一份相当顶饿。', 'Thick filling rests on a thin base, with a mild pumpkin sweetness and a substantial portion.'],
  cake: ['白糖霜覆着松软糕体，摆稳后可以一口口分着吃。', 'White icing covers a soft cake that can be shared bite by bite once set down.'],
  mushroom_stew: ['两种蘑菇浮在褐汤里，盛满一碗就是简单的一顿。', 'Two kinds of mushroom sit in brown broth, a full bowl making a simple meal.'],
  beetroot_soup: ['红汤里留着细碎根肉，味道平淡，热量倒够一顿。', 'Fine root pieces remain in the red broth, mild in flavour but enough for a meal.'],
  rabbit_stew: ['肉、菌和菜块把碗盛得很满，一份就足够应付长路。', 'Meat, mushrooms and vegetables fill the bowl, enough to support a long stretch of travel.'],
  suspicious_stew: ['汤里藏着辨不清的花叶，闻得出草味，却猜不准喝下去的反应。', 'Unfamiliar petals hide in the broth, herbal in scent but uncertain in effect.'],
  honey_bottle: ['金色蜜液缓缓挂住瓶壁，甜味很足，喝完还留得住瓶子。', 'Golden honey slowly coats the glass, sweet and leaving the bottle available afterward.'],
  egg: ['薄硬壳包着蛋液，做饼时用得上，掷出去也可能孵出小鸡。', 'A thin hard shell holds the egg, useful in baking or occasionally hatching when thrown.'],
  wheat: ['饱满谷粒排在干穗上，磨进面包或喂给牲畜都不浪费。', 'Full grains line the dry ear, useful in bread or as livestock feed.'],
  sugar: ['细白晶粒轻轻一碰就散开，做糕点和酿药都要用。', 'Fine white crystals scatter at a touch, needed in both baking and brewing.'],
});

Object.assign(lore, {
  brewing_stand: ['细管分出三个瓶位，添上烈焰粉才能把药慢慢酿起来。', 'A narrow column branches into three bottle rests, needing blaze powder to begin brewing.'],
  glass_bottle: ['薄玻璃围出一只小瓶，洗净后装水和收蜜都方便。', 'Thin glass forms a little vessel, convenient for water or honey once clean.'],
  potion: ['药液在细颈瓶里轻晃，效力要看其中实际酿进了什么。', 'Liquid shifts inside the narrow-necked bottle, its effect depending on what was brewed into it.'],
  splash_potion: ['瓶口封得很紧，薄壳掷碎后药液会洒向周围。', 'A tight seal closes the thin bottle, which scatters its contents when thrown.'],
  lingering_potion: ['稠密药液在瓶里转得很慢，落地碎开后会留下一团药雾。', 'Dense liquid turns slowly in the bottle and leaves a cloud after it breaks.'],
  tipped_arrow: ['箭尖蘸过药液，射中时能把这份药效一起带过去。', 'Potion coats the arrowhead, carrying its effect into a successful shot.'],
  dragon_breath: ['紫色气息贴着瓶壁翻卷，是酿出滞留药雾的关键材料。', 'Purple breath rolls against the glass, material needed for a lingering potion.'],
  nether_wart: ['暗红小粒结在短茎上，大多数药水都从它开头。', 'Dark-red knobs gather on a short stem, the beginning of most potions.'],
  ominous_bottle: ['蓝色瓶液显得阴沉，打开喝下会招来不祥的兆头。', 'The blue liquid looks sombre and brings an ill omen when drunk.'],
  experience_bottle: ['绿色光点浮在瓶里，摔开才能把积下的经验放出来。', 'Green lights float inside the bottle, releasing their experience when broken.'],
  blaze_powder: ['炽黄粉末摸着发暖，能给酿造台补火，也能配力量药水。', 'Hot-yellow powder feels warm, fuelling a brewing stand or making strength potions.'],
  magma_cream: ['橙色黏团裹着热意，酿出的药能让人经得起火。', 'The sticky orange mass holds heat and brews into protection from fire.'],
  fermented_spider_eye: ['发酵后的眼珠气味尖锐，足以把原有药性改个方向。', 'A sharp smell rises from the fermented eye, enough to turn a potion\'s effect around.'],
  gunpowder: ['灰黑粉末细而干，混进配方后会让平常物件有爆裂的本事。', 'Fine dry grey-black powder gives a mixture the means to burst apart.'],
  glowstone_dust: ['金色细屑亮得均匀，少量就能增强某些药水的效力。', 'Evenly bright golden grains strengthen certain potions in small amounts.'],
  glistering_melon_slice: ['金粒围住一片红瓤，虽然不能当饭，却能用来酿治疗药。', 'Gold surrounds a red slice, unsuitable as a meal but useful in healing potions.'],
  rabbit_foot: ['细骨裹着短绒，酿进药水能让脚下多些弹力。', 'Short fur covers fine bones, an ingredient that adds spring to a potion.'],
  phantom_membrane: ['薄膜轻韧透光，既能补鞘翅，也能酿出缓降药。', 'A light, tough membrane passes light through and serves for elytra repair or slow falling.'],
  ghast_tear: ['乳白小滴结成硬珠，拿去酿药能慢慢补回伤势。', 'A milky drop has set into a firm bead, useful in a potion that restores health over time.'],
});

Object.assign(lore, {
  redstone: ['暗红粉末铺开就连成细线，接上电源才能把信号送出去。', 'Dark red dust lays into a fine trail that carries a signal from a power source.'],
  redstone_block: ['红色粉末压成致密硬块，贴着线路就能持续供能。', 'Red powder is pressed into a dense block that supplies steady power to a circuit.'],
  redstone_torch: ['小棍上的红光很弱，放进线路却能反转送来的信号。', 'The red light is weak, though its place in a circuit can invert an incoming signal.'],
  repeater: ['两根细柱排在石板上，调开距离就能让信号迟些传到。', 'Two posts line the stone plate, adjustable to delay a passing signal.'],
  comparator: ['三根细柱围着石座，容器里存了多少也能变成信号。', 'Three posts surround the stone base, turning a container\'s contents into a readable signal.'],
  piston: ['木面装在伸缩铁杆前端，通电后能把前面的方块推开。', 'A wooden face caps the sliding iron rod and pushes a block when powered.'],
  sticky_piston: ['活塞木面糊着绿色黏液，伸出去以后还能把东西拉回来。', 'Green slime coats the piston face so it can pull a block back after extending.'],
  observer: ['石壳一面留着探孔，前方有变化就从背后送出短促信号。', 'Openings mark one side of the stone casing, sending a brief signal from the back when the front changes.'],
  dispenser: ['石壳里装着弹射机构，里面放什么决定它会怎样出手。', 'A firing mechanism sits inside the stone shell, acting according to what it holds.'],
  dropper: ['方正石盒留着一个出口，通电后能把里面一件东西送出去。', 'A square stone box has one outlet, releasing one item when powered.'],
  hopper: ['宽铁口收向细管，接在容器下面就能慢慢传走东西。', 'A broad iron mouth narrows into a pipe that gradually transfers items beneath a container.'],
  crafter: ['台面九格各有定位，安排好空位便能按脉冲逐次合成。', 'Nine fixed positions fill the top, assembling a recipe on each pulse once its slots are set.'],
  tnt: ['红色药卷紧紧捆成一块，点着引线后得赶紧离远些。', 'Red explosive rolls bind tightly together, calling for distance once the fuse is lit.'],
  tripwire_hook: ['弯铁钩装在小木座上，绷起细线就能察觉经过的人。', 'A bent iron hook sits on a wooden base, detecting a passerby along a taut thread.'],
  lever: ['短柄在石座上转动，拨到哪一边就保持那种开关状态。', 'A short handle pivots on stone and holds the selected switch position.'],
  daylight_detector: ['平整玻璃盖着感光表面，日光强弱会变成不同的信号。', 'Flat glass covers a sensing face that turns daylight strength into a changing signal.'],
  note_block: ['木盒里留着共鸣空腔，底下垫的材料会改变敲出的音色。', 'A hollow wooden box resonates differently according to the material beneath it.'],
  redstone_lamp: ['深色框条分开暖色灯面，接到红石信号才会亮起来。', 'Dark strips divide the warm-coloured face, which lights when given a redstone signal.'],
  target: ['红色靶心画在草捆上，射得越准，送出的信号越强。', 'A red centre marks the straw bundle, giving a stronger signal for a closer shot.'],
  trapped_chest: ['木箱扣件连着细小机关，盖子一开就会惊动相邻线路。', 'A small mechanism joins the chest latch, alerting a neighbouring circuit as the lid opens.'],
  sculk_sensor: ['柔细触须从暗色底座伸出，脚步和动作都会惊动它。', 'Fine tendrils rise from a dark base, responding to footsteps and nearby actions.'],
  calibrated_sculk_sensor: ['紫晶嵌在触须旁边，接入侧面的信号能筛选它听见的动静。', 'Amethyst sits beside the tendrils, with a side input filtering the vibrations it hears.'],
  slime_block: ['半透明绿胶柔软回弹，既能缓冲落地，也能带着邻块一起移动。', 'Translucent green gel rebounds softly, cushioning falls and moving neighbouring blocks.'],
  honey_block: ['厚蜜凝成金色方块，表面很黏，碰着边走就会慢下来。', 'Thick honey forms a golden block whose sticky sides slow a passing body.'],
  rail: ['两根铁轨架在木枕上，接顺了便能让矿车通行。', 'Two iron rails rest on wooden sleepers, carrying a minecart along a connected route.'],
  powered_rail: ['金色轨条间排着红石，通电后能给矿车添一把力。', 'Redstone lies between golden rails and gives a minecart a push when powered.'],
  detector_rail: ['轨道中间嵌着感应板，矿车压过就能报出一个信号。', 'A sensing plate sits between the rails and reports a passing minecart.'],
  activator_rail: ['红石构件横在铁轨之间，能触发经过矿车的特殊动作。', 'A redstone fitting crosses the rails to trigger a passing minecart\'s special action.'],
  minecart: ['铁斗底下装着小轮，走轨道时能载人也能载货。', 'Small wheels carry the iron tub along rails with a passenger or an added load.'],
  chest_minecart: ['木箱固定在铁斗里，装满后可以整车送去别处。', 'A wooden chest sits firmly in the iron tub, ready to send its load elsewhere.'],
  hopper_minecart: ['车斗换成了收集铁口，沿轨道走就能捡起上方的散物。', 'A gathering mouth replaces the tub and collects loose items as it travels.'],
  furnace_minecart: ['小石炉嵌在车斗上，添进煤炭就能推着别的车走。', 'A small stone furnace fills the tub and pushes other carts with a supply of coal.'],
  tnt_minecart: ['炸药牢牢放在车斗里，运到指定位置再点火才稳妥。', 'Explosives sit firmly inside the cart, best moved into position before ignition.'],
  lightning_rod: ['细长铜杆收向尖端，架高后能把雷引到选好的地方。', 'A long copper rod narrows to a point and draws lightning toward a chosen elevated position.'],
  light_weighted_pressure_plate: ['薄金板轻轻压下便有回应，承上去的物件越多信号越强。', 'A thin gold plate responds to a light load and strengthens its signal as items accumulate.'],
  heavy_weighted_pressure_plate: ['铁板厚实，少量东西只能压出弱信号，适合感知较大的堆积。', 'A sturdy iron plate gives little response to a small load and suits a larger accumulation.'],
  stone_button: ['小石块磨出可按的平面，手指一推就送出一段短信号。', 'A little stone block has a flat pressing face that sends a short pulse under a finger.'],
  stone_pressure_plate: ['薄石板略高出底座，脚踩上去才会稳稳接通。', 'A thin stone plate sits above its base and connects under a standing foot.'],
  polished_blackstone_button: ['磨黑的石钮表面平滑，装在暗墙上不太显眼。', 'A polished black button has a smooth face and sits discreetly on a dark wall.'],
  polished_blackstone_pressure_plate: ['黑石薄板边缘磨齐，压在门前能让脚步变成信号。', 'Neat edges line the black stone plate, turning a doorstep into a signal.'],
});
const woodNames = { acacia: ['金合欢', 'acacia'], bamboo: ['竹', 'bamboo'], birch: ['白桦', 'birch'], cherry: ['樱花', 'cherry'], crimson: ['绯红', 'crimson'], dark_oak: ['深色橡木', 'dark oak'], jungle: ['丛林木', 'jungle wood'], mangrove: ['红树', 'mangrove'], oak: ['橡木', 'oak'], spruce: ['云杉', 'spruce'], warped: ['诡异', 'warped'] };
for (const [id, [zh, en]] of Object.entries(woodNames)) {
  pair(`${id}_button`, `${zh}木纹沿小钮横过，手按或箭射都能送出一段信号。`, `${en[0].toUpperCase()}${en.slice(1)} grain crosses the little button, which responds to a finger or an arrow.`);
  pair(`${id}_pressure_plate`, `${zh}薄板贴着底座，落在上面的物件也能把它压响。`, `A thin ${en} plate rests on its base, responding even to an item dropped on top.`);
}
for (const [stage, zh, en] of [['', '红铜外壳还很鲜亮', 'The fresh copper shell is still bright'], ['exposed_', '铜壳上开始冒出暗斑', 'Dark patches have begun to mark the copper shell'], ['weathered_', '绿锈已经爬过大半铜壳', 'Patina has crossed most of the copper shell'], ['oxidized_', '整面铜壳已经转成青绿', 'The whole copper shell has turned blue-green']]) {
  pair(`${stage}copper_bulb`, `${zh}，接一次脉冲就能改变亮灭，氧化越深光越弱。`, `${en}; a pulse changes its lit state, and deeper oxidation dims the light.`);
  pair(`waxed_${stage}copper_bulb`, `${zh}，薄蜡封住现有颜色和亮度，适合调好以后长用。`, `${en}; a thin wax seal preserves its present colour and brightness for lasting use.`);
}

Object.assign(lore, {
  stick: ['削直的小木棍还留着细纹，做柄、搭架和点火都能派上用场。', 'Fine grain remains on the straight little stick, useful for handles, frames and kindling.'],
  string: ['细丝搓得匀细，拉弓、织布和绊线机关都少不了它。', 'Even fine threads are useful for bowstrings, weaving and tripwire mechanisms.'],
  leather: ['柔韧皮面带着浅浅褶痕，裁开能缝护具，也能包书。', 'Shallow creases mark the supple hide, ready for armour or a book cover.'],
  feather: ['轻羽两侧排列齐整，做箭尾能稳住飞行，书写也用得上。', 'Even vanes line the light quill, useful for steady arrow flight or writing.'],
  bone: ['硬白骨节中间留着空腔，磨成骨粉后能给植物补养分。', 'A hollow runs through the hard white bone, which grinds into plant-feeding meal.'],
  bone_meal: ['白色细粉里夹着碎粒，撒到合适的植物上便能催它长一截。', 'White powder carries small fragments and encourages a suitable plant to grow.'],
  charcoal: ['烧黑的木纹仍看得清，拿来冶炼和制火把都很实在。', 'Wood grain remains in the blackened lump, sound material for smelting or torches.'],
  flint: ['灰黑薄石断面锋利，配上铁片能擦火，也能制箭头。', 'Sharp edges split the grey-black stone, useful for arrowheads or sparks against iron.'],
  clay_ball: ['湿黏土团没有棱角，送进炉里就能烧成一块小砖。', 'The damp clay lump has no sharp edges and fires into a small brick.'],
  brick: ['烧红的小砖边角齐整，砌成砖块或捏出花盆都用得上。', 'Neat edges line the little fired brick, useful in brickwork or a flowerpot.'],
  nether_brick: ['暗红小砖烧得坚硬，攒起几块就能砌出下界砖墙。', 'The dark-red fired brick is hard, ready to gather into Nether brickwork.'],
  paper: ['薄纸纤维细密，写地图、装订书和卷烟花都方便。', 'Fine fibres make the thin sheet useful for maps, books and firework rolls.'],
  book: ['纸页整齐缝进皮封，既能继续书写，也能承住附魔。', 'Even pages are sewn into a leather cover, ready for writing or enchantment.'],
  writable_book: ['羽笔夹在空白页间，翻开就能记下路程和见闻。', 'A quill sits among blank pages, ready to record a route or an observation.'],
  written_book: ['墨迹已经落定，翻阅能读出原话，再复制也不会改动内容。', 'The ink has settled into a finished text that remains unchanged when copied.'],
  enchanted_book: ['字迹在书页间泛光，放上铁砧就能把合适的附魔传给装备。', 'Writing glows between the pages, transferring a suitable enchantment at an anvil.'],
  prismarine_shard: ['青绿石片断口参差，拼起来仍能还原神殿的石材。', 'Uneven breaks line the blue-green shard, still useful in rebuilding monument stone.'],
  prismarine_crystals: ['透亮小晶簇泛着海绿色，组合后能做出水下的灯。', 'Clear little clusters hold a sea-green tint, material for an underwater lamp.'],
  quartz: ['乳白晶体棱角清楚，建筑装饰和红石元件都要用。', 'Distinct edges shape the milky crystal, needed in decorative blocks and redstone fittings.'],
  turtle_scute: ['小块硬壳边缘微弯，拼齐以后能做贴头的海龟壳。', 'The hard piece curves at its edge and joins others into a fitted turtle shell.'],
  armadillo_scute: ['角质甲片坚韧带弧，叠起来能护住狼的身体。', 'Curved, tough plates overlap into protection for a wolf\'s body.'],
  rabbit_hide: ['小片软皮边缘不整，攒够几张才能合成一张皮革。', 'The little soft hide has uneven edges and needs companions to make a full leather piece.'],
  honeycomb: ['六角蜡房挂着蜜香，做蜂箱、蜡烛和封铜都合适。', 'Hexagonal wax cells smell faintly of honey, useful for hives, candles and sealing copper.'],
  shulker_shell: ['紫色硬壳轻而结实，两片合起来能护住会搬动的储物箱。', 'A light, tough purple shell pairs with another to protect portable storage.'],
  echo_shard: ['深色晶片里透着青光，配进指南针能指回最后倒下的地方。', 'Blue-green light sits inside the dark shard, guiding a compass toward the last place of death.'],
  disc_fragment_5: ['黑色薄片边沿参差，凑齐同样的碎片才能补成一张唱片。', 'Uneven edges break the thin black piece, requiring matching fragments to restore a disc.'],
  nautilus_shell: ['浅色壳沿着细纹盘起，配上海洋之心才有潮涌核心的用处。', 'Fine lines follow the pale spiral, useful with a heart of the sea in a conduit.'],
  blaze_rod: ['黄色长杆里存着热意，磨粉能酿药，整根也能做酿造台。', 'Heat remains in the yellow rod, useful whole in a brewing stand or ground into powder.'],
  breeze_rod: ['灰紫细杆轻得异常，拆成风弹或装进重锤都合用。', 'The grey-purple rod is unusually light, suitable for wind charges or a mace.'],
  ender_pearl: ['暗绿珠面透着深光，投出去就能把人带到落点。', 'Deep light sits beneath the dark-green surface, carrying its thrower to the landing point.'],
  ender_eye: ['绿色圆珠中间嵌着瞳孔，放飞时会朝要塞方向走。', 'A pupil sits in the green sphere, which travels toward a stronghold when released.'],
  lapis_lazuli: ['深蓝矿粒染色很牢，在附魔台前也要备上一些。', 'Deep-blue mineral grains hold their colour firmly and are needed at an enchanting table.'],
  snowball: ['松雪揉成小团，掷出去会散开，遇到烈焰人倒有些用。', 'Loose snow is pressed into a little ball that breaks on impact and proves useful against blazes.'],
  cocoa_beans: ['褐色豆粒带着苦香，烘进曲奇或磨作棕色染料都好用。', 'Brown beans carry a bitter scent, suitable for cookies or brown dye.'],
  ink_sac: ['薄囊里装着浓黑墨汁，染色或配书写材料都足够。', 'A thin sac holds dense black ink for dyeing or preparing writing supplies.'],
  glow_ink_sac: ['墨液里浮着微光，涂在告示牌上能让字迹在暗处显出来。', 'Faint light floats in the ink, making sign lettering visible in the dark.'],
  slime_ball: ['半透明胶团黏手又有弹性，装活塞和搓拴绳都用得上。', 'The translucent lump sticks and springs back, useful for pistons or leads.'],
  heavy_core: ['暗铁方芯沉得压手，装进重锤后这份重量就有了用处。', 'The dark iron core weighs heavily in the palm, weight put to use in a mace.'],
  trial_key: ['铜色钥匙齿形分明，找到普通宝库才有锁可开。', 'Distinct teeth line the copper-coloured key, suited to an ordinary vault.'],
  ominous_trial_key: ['暗色钥匙泛着蓝光，只有不祥宝库能与它的齿口吻合。', 'Blue light marks the dark key, whose teeth fit only an ominous vault.'],
  gold_ingot: ['暖黄金属压成长条，做零件、配金食物和与猪灵交易都方便。', 'Warm yellow metal is cast into a bar for fittings, gilded food or bartering with piglins.'],
  copper_ingot: ['红铜表面细腻发亮，锻成避雷针或压成建筑材料都合适。', 'Fine red copper shines at the surface, suitable for a lightning rod or building stock.'],
  iron_nugget: ['细小铁粒沉在掌心，凑成锭或装灯笼都不会浪费。', 'A tiny iron piece has weight in the palm, useful gathered into an ingot or a lantern.'],
  gold_nugget: ['小金粒亮得清楚，配胡萝卜或压成金锭都很方便。', 'The little gold piece shines distinctly, useful with a carrot or pressed into an ingot.'],
  raw_iron: ['褐色岩皮裹着发亮的铁粒，进炉烧过才好加工。', 'Brown rocky skin encloses bright iron grains that need smelting before use.'],
  raw_gold: ['灰褐岩壳里嵌着金色颗粒，熔开以后才能铸成整锭。', 'Gold grains sit in a grey-brown shell, ready to melt into a complete ingot.'],
  raw_copper: ['红绿矿粒结成不规则团块，烧净杂质便是一锭铜料。', 'Red and green grains form an uneven lump that smelts into workable copper.'],
  ancient_debris: ['深褐断面挤着层纹，火也烧不坏，得进炉炼出其中的碎料。', 'Tight layers cross the deep-brown fracture, resistant to fire but yielding scrap in a furnace.'],
  netherite_scrap: ['烧炼后的暗色碎片薄而硬，和金锭合在一起才能继续锻造。', 'Thin hard scraps remain after smelting and need gold before further forging.'],
  netherite_upgrade_smithing_template: ['红色底片里嵌着升级纹路，铁匠台能照着它把钻石装备改成下界合金。', 'An upgrade pattern sits in the red base, guiding the smithing table from diamond to netherite.'],
});
const seeds = {
  wheat_seeds: ['细绿种粒轻得几乎感觉不到', 'Fine green seeds are almost weightless', '小麦', 'wheat'],
  beetroot_seeds: ['小褐种粒外壳粗糙', 'Small brown seeds have rough coats', '甜菜根', 'beetroot'],
  melon_seeds: ['浅褐种子边缘扁平', 'Pale brown seeds have flat edges', '西瓜', 'melons'],
  pumpkin_seeds: ['白色种片薄而宽', 'White seed pieces are thin and broad', '南瓜', 'pumpkins'],
  torchflower_seeds: ['暗色种子裹着坚实外皮', 'Dark seeds wear firm coats', '火把花', 'torchflowers'],
  pitcher_pod: ['圆润种荚里鼓着新芽', 'A rounded pod encloses a new shoot', '瓶子草', 'pitcher plants'],
};
for (const [id, [zh, en, cropZh, cropEn]] of Object.entries(seeds)) pair(id, `${zh}，埋进耕地才能长成${cropZh}。`, `${en} and need farmland to grow into ${cropEn}.`);
const trims = {
  bolt: ['镶在边缘的铆钉', 'rivets set along an edge'], coast: ['海岸般的曲线', 'curves like a shoreline'], dune: ['沙丘般的条纹', 'bands like sand dunes'],
  eye: ['中央的眼形', 'a central eye'], flow: ['回旋的气流', 'turning currents'], host: ['相连的古纹', 'joined ancient marks'], raiser: ['向上叠起的层线', 'rising layered lines'],
  rib: ['成列的肋骨', 'rows of ribs'], sentry: ['整齐的守卫条带', 'ordered sentry bands'], shaper: ['转折分明的折线', 'sharply turning lines'], silence: ['密布的幽暗纹路', 'close-set dark patterns'],
  snout: ['方正的鼻口', 'a squared snout'], spire: ['修长的塔线', 'long spire lines'], tide: ['重叠的潮水', 'overlapping tides'], vex: ['尖细的翼形', 'narrow wing shapes'],
  ward: ['胸前的监守纹', 'a warding chest pattern'], wayfinder: ['通往四方的路径', 'paths reaching outward'], wild: ['交错的丛林刻痕', 'crossing jungle cuts'],
};
for (const [id, [zh, en]] of Object.entries(trims)) pair(`${id}_armor_trim_smithing_template`, `薄片刻着${zh}，压到护甲上只添纹饰，不改变防护。`, `The template carries ${en}, adding decoration to armour without changing its protection.`);
const sherds = {
  angler: ['一尾鱼', 'a fish'], archer: ['弯弓', 'a bent bow'], arms_up: ['举起的双臂', 'raised arms'], blade: ['直剑', 'a straight sword'], brewer: ['药瓶', 'a potion bottle'], burn: ['火焰', 'flames'],
  danger: ['警示的图形', 'a warning figure'], explorer: ['探路的图案', 'an exploring figure'], flow: ['回旋的线条', 'turning lines'], friend: ['相伴的身影', 'a companion figure'], guster: ['风的轮廓', 'the outline of a gust'],
  heart: ['完整的心形', 'a whole heart'], heartbreak: ['裂开的心形', 'a broken heart'], howl: ['昂首的狼', 'an upturned wolf head'], miner: ['矿镐', 'a mining pick'], mourner: ['低垂的身影', 'a bowed figure'],
  plenty: ['丰收的形状', 'a sign of plenty'], prize: ['奖赏的图样', 'a prize motif'], scrape: ['刮刷的记号', 'a scraping mark'], sheaf: ['成束的麦穗', 'a sheaf of wheat'], shelter: ['树木般的庇护', 'tree-like shelter'],
  skull: ['骷髅', 'a skull'], snort: ['嗅探兽的轮廓', 'a sniffer outline'],
};
for (const [id, [zh, en]] of Object.entries(sherds)) pair(`${id}_pottery_sherd`, `陶片边缘断得参差，表面还留着${zh}，拼进陶罐就能保留这幅图。`, `Uneven edges surround ${en} on the clay shard, a picture preserved by setting it into a decorated pot.`);
const patterns = { creeper: ['苦力怕的脸', 'a creeper face'], flow: ['盘旋的涡纹', 'a turning swirl'], flower: ['花形', 'a flower'], globe: ['球形经纬', 'a globe'], guster: ['旋风的轮廓', 'a gust outline'], mojang: ['古怪的纹章', 'an unusual emblem'], piglin: ['猪鼻形状', 'a piglin snout'], skull: ['骷髅面孔', 'a skull face'] };
for (const [id, [zh, en]] of Object.entries(patterns)) pair(`${id}_banner_pattern`, `纸样画着${zh}，放在织机旁就能把同样的图织进旗面。`, `The paper pattern shows ${en}, ready to guide the same image into a banner at a loom.`);

Object.assign(lore, {
  bowl: ['浅木碗内侧刮得平滑，盛汤吃完以后还能接着用。', 'The shallow wooden bowl is scraped smooth inside and ready for another helping after use.'],
  creeper_head: ['绿皮留着方正的五官，戴上能让同类稍晚察觉靠近的人。', 'Square features remain in the green skin, delaying a creeper\'s notice of the wearer.'],
  zombie_head: ['青绿面皮已经僵硬，戴着能缩短僵尸注意到人的距离。', 'The green face has stiffened, reducing the distance at which zombies notice its wearer.'],
  skeleton_skull: ['白骨眼窝空着，戴起来能让骷髅稍晚认出眼前的人。', 'Empty eye sockets mark the white bone, making skeletons slower to notice its wearer.'],
  wither_skeleton_skull: ['黑色骨面沉而粗糙，摆进灵魂沙阵里可不是普通装饰。', 'Dark bone is heavy and rough, more than decoration when placed in a soul-sand formation.'],
  piglin_head: ['宽耳垂在金褐面皮两侧，接上红石还能轻轻摆动。', 'Broad ears hang beside the gold-brown face and move when supplied with redstone.'],
  dragon_head: ['黑色长颌连着粗大的角，接通红石就能让嘴一张一合。', 'A long black jaw joins stout horns, opening and closing under redstone power.'],
  dragon_egg: ['紫黑卵壳厚重发亮，轻碰就挪走位置，收起时得另想办法。', 'The purple-black shell is thick and bright, shifting away at a touch and requiring care to collect.'],
  end_crystal: ['粉色晶体浮在细框中，碰碎会猛烈爆炸，安放时要留空地。', 'A pink crystal floats in a fine frame, exploding violently when broken and needing clear space.'],
  totem_of_undying: ['小金像双眼透绿，握在手里才能在致命一击时替人撑住。', 'Green eyes shine in the little gold figure, which must be held to withstand a fatal blow.'],
});
for (const [id, [zh, en]] of Object.entries(woodNames)) {
  if (id === 'crimson' || id === 'warped' || id === 'bamboo') continue;
  pair(`${id}_boat`, `${zh}船板围着浅舱，两支木桨足够带两位乘客过水。`, `${en[0].toUpperCase()}${en.slice(1)} planks enclose a shallow hull, with two oars enough to carry two passengers across water.`);
  pair(`${id}_chest_boat`, `${zh}船舱让出一半给木箱，一个人就能连货物一起划走。`, `Half the ${en} hull is set aside for a chest, letting one rower carry a load across water.`);
}
pair('bamboo_raft', '竹节捆成宽而平的筏面，两人坐稳就能划过水面。', 'Bound bamboo makes a broad flat deck that carries two seated passengers across water.');
pair('bamboo_chest_raft', '竹筏上绑着一只木箱，货物有了地方，划船的人就只剩一个座。', 'A chest is tied to the bamboo deck, leaving one seat for the rower beside the load.');
const discs = {
  '11': ['唱片边缘已经残破，针槽里留着急促脚步和粗重呼吸。', 'The disc edge is broken, its grooves holding hurried steps and heavy breathing.'],
  '13': ['暗色唱片刻着细槽，放进唱片机便响起空洞的回声。', 'Fine grooves cross the dark disc and play hollow echoes in a jukebox.'],
  '5': ['拼回的唱片仍带着接痕，断续的声响听来像一段未讲清的经历。', 'Joins remain in the restored disc, its broken sounds suggesting an unfinished account.'],
  blocks: ['橙色中心衬着黑盘，明快的旋律适合在忙活时听。', 'An orange centre marks the black disc, with a lively tune for a stretch of work.'],
  cat: ['绿色中心很醒目，轻快的电子音能给空屋添些动静。', 'A green centre marks a light electronic tune that gives an empty room some life.'],
  chirp: ['红色中心旁的槽纹细密，老唱机般的曲调很容易认出来。', 'Fine grooves surround a red centre, playing a readily recognisable old-record tune.'],
  far: ['青绿中心压在薄黑盘上，舒展的旋律听着很空阔。', 'A blue-green centre sits on the thin black disc, carrying an open, unhurried melody.'],
  mall: ['紫色圆心边缘整齐，温和的曲调适合填满安静的房间。', 'A neat purple centre marks a gentle tune that fills a quiet room.'],
  mellohi: ['紫白中心像小小旋纹，缓慢的圆舞节拍带着旧日气息。', 'Purple and white turn in the centre, with a slow waltz rhythm that sounds well worn.'],
  stal: ['近乎全黑的唱片不起眼，爵士节拍里夹着清楚的笛声。', 'The nearly black disc is plain, with a clear recorder voice over its jazz rhythm.'],
  strad: ['白色中心干净明亮，舒缓的曲调听着像从远处传来。', 'A clean white centre marks an easy tune that seems to arrive from a distance.'],
  ward: ['暗绿中心沉在黑盘里，庄重开头后接着更轻快的旋律。', 'A dark-green centre sits in the black disc, moving from a solemn opening into a lighter tune.'],
  wait: ['蓝色中心颜色很深，熟悉的旋律换上了轻松的节拍。', 'A deep-blue centre marks a familiar melody set to an easy rhythm.'],
  pigstep: ['红盘里嵌着金色中心，低沉有力的节拍很适合宽阔的厅堂。', 'A gold centre sits in the red disc, with a firm low beat that fills a broad hall.'],
  otherside: ['蓝绿圆心带着亮色，曲调从清淡慢慢铺得热闹起来。', 'Bright blue-green marks the centre as the tune grows from light phrases into a fuller arrangement.'],
  relic: ['棕色中心像旧陶面，平缓的电子旋律适合慢慢听完。', 'A brown centre resembles old clay, with an even electronic tune worth hearing through.'],
  creator: ['黄绿色中心边缘鲜明，旋律层层展开，能把屋里的安静填满。', 'A clear yellow-green centre marks a tune that builds in layers to fill a quiet room.'],
  creator_music_box: ['浅黄圆心像细小机芯，同一支曲子换成了清脆的八音盒声。', 'The pale-yellow centre resembles a little mechanism, playing the tune in clear music-box notes.'],
  precipice: ['暗色唱片围着紫灰圆心，紧密的节拍听着像在一步步逼近。', 'Dark grooves circle a purple-grey centre, their close rhythm steadily approaching.'],
};
for (const [id, copy] of Object.entries(discs)) lore[`music_disc_${id}`] = copy;
